version: '3.9'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./log_service:/app/log_service
    expose:
      - "29501"
      - "29502"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "29501:29501"
      - "29502:29502"
    depends_on:
      - flask